DRIVERS-2033 Use OP_MSG when 'loadBalanced=True'
mongodb/specifications pull request #1123
Opened 2022-01-18 23:28 UTC by juliusgeo

2022-01-19 12:38 UTC, blink1073 submitted a review, later dismissed
Do we need a new spec source demonstrating this behavior?

2022-01-19 13:10 UTC, juliusgeo commented
@blink1073 See [the previous OP_MSG ticket](https://jira.mongodb.org/browse/DRIVERS-1873?filter=-1)

"Investigate whether it is practical to specify a test to validate this behavior. Failpoints cannot distinguish wire protocol versions. There may be no way to practically test this until SERVER-59085 is complete. After SERVER-59085 is complete, this will be tested in existing driver tests against the latest built servers (by virtue of authentication succeeding)."

2022-01-19 13:12 UTC, blink1073 approved these changes
LGTM!

2022-01-19 21:18 UTC, ShaneHarvey requested changes
@juliusgeo I think this change warrants being implemented in pymongo before we merge. I'd like to make sure that the Serverless tests still pass.

2022-01-19 21:18 UTC, ShaneHarvey commented on source/mongodb-handshake/handshake.rst
> +compatibility), and include ``helloOk:true``in the handshake request.
There's a missing space:
```
``helloOk:true``in
```

2022-01-25 18:42 UTC, ShaneHarvey approved these changes
LGTM, I suggest renaming the PR title and the commit message to include the "hello" command requirement to be a little more informative. For example, "DRIVERS-2033 Require hello command + OP_MSG when 'loadBalanced=True'"

2022-01-26 00:27 UTC, juliusgeo commented
As per @ShaneHarvey's about serverless tests passing in PyMongo with this change:
- [Evergreen build with serverless, load balancer and versioned api tests passing](https://evergreen.mongodb.com/version/61ef62df0ae6062a0ba30101?redirect_spruce_users=true) and [the corresponding commit](https://github.com/mongodb/mongo-python-driver/pull/837/commits/6587126930b8c502fc1f49241082d7b24d790584)
- [The PR](https://github.com/mongodb/mongo-python-driver/pull/837)

2022-01-26 00:42 UTC, JamesKovacs approved these changes
LGTM

2022-01-26 16:19 UTC, durran approved these changes
LGTM

2022-01-26 16:19 UTC, merged