DRIVERS-1343 Include the "to" field in ChangeStreamDocument
mongodb/specifications pull request #1138
Opened 2022-02-09 18:40 UTC by abr-egn

2022-02-10 15:15 UTC, benjirewis requested changes
Awesome! You'll also want to update the "last updated" date, bump the minor version of the spec, and add to the bottom of the changelog. Also, is there any way we can add a spec test to ensure that a [rename change event](https://docs.mongodb.com/manual/reference/change-events/#rename-event) will include the new `to` field?

2022-03-14 16:52 UTC, abr-egn commented
Should be good for another look - updated the spec tracking info and added a test.

2022-03-15 18:22 UTC, benjirewis approved these changes
LGTM thanks!

2022-03-31 14:33 UTC, merged

2022-03-31 20:28 UTC, jmikola commented on source/change-streams/tests/unified/change-streams.yml
> +      - name: rename
Oh, I didn't realize there was already another PR that added a `rename` operation. And this test file uses `schemaVersion: "1.0"`.

I think that can change our approach in https://github.com/mongodb/specifications/pull/1156#discussion_r839959883 and we can safely just start adding `rename` to test files without bumping the schema version, as any driver implementing a downstream ticket for [DRIVERS-1343](https://jira.mongodb.org/browse/DRIVERS-1343) is going to encounter this already.