DRIVERS-1150 Writes are not retried within transactions
mongodb/specifications pull request #1481
Opened 2023-12-06 13:14 UTC by comandeo

Please complete the following before merging:

- [x] Update changelog.
- [ ] _Make sure there are generated JSON files from the YAML test files - not applicable._
- [ ] _Test changes in at least one language driver - not applicable._ 
- [ ] _Test these changes against all server versions and topologies (including standalone, replica set, sharded clusters, and serverless) - not applicable._

2023-12-14 20:46 UTC, kkloberdanz requested changes

2023-12-14 20:46 UTC, kkloberdanz commented on source/retryable-writes/retryable-writes.rst
> +Retryable Writes Withing Transactions
```suggestion
Retryable Writes Within Transactions
```

2023-12-14 20:48 UTC, kkloberdanz commented
Hi Dmitry, is there any background information for this change that you would be able to share with us on this PR? Also, does it make sense to have a test for this behavior? Thank you.

2023-12-14 21:12 UTC, isabelatkinson approved these changes
LGTM with a few suggestions, I don't need to do another round of review

@kkloberdanz I see the following comment on DRIVERS-1150:
> This is a simple but important clarification for non-engineer audiences. It requires no driver changes or new tests.

2023-12-14 21:12 UTC, isabelatkinson commented on source/retryable-writes/retryable-writes.rst
> +:2023-12-06: Clarify that writes are not retried with transactions.
```suggestion
:2023-12-06: Clarify that writes are not retried within transactions.
```

2023-12-14 21:12 UTC, isabelatkinson commented on source/retryable-writes/retryable-writes.rst
> +enabled on the ``MongoClient``. In addition, drivers MUST NOT add
```suggestion
set to true on the ``MongoClient``. In addition, drivers MUST NOT add
```

2023-12-14 21:12 UTC, isabelatkinson commented on source/retryable-writes/retryable-writes.rst
> +and ``abortTransaction``), even when ``retryWrites`` has been enabled on
```suggestion
and ``abortTransaction``), even when ``retryWrites`` has been set to true on
```

2023-12-14 21:12 UTC, isabelatkinson commented on source/retryable-writes/retryable-writes.rst
> +enabled on the ``MongoClient``. In addition, drivers MUST NOT add
this sounds a little more clear to me but feel free to accept or reject, ditto below

2023-12-15 14:20 UTC, kkloberdanz commented
> > Hi Dmitry, is there any background information for this change that you would be able to share with us on this PR? Also, does it make sense to have a test for this behavior? Thank you.
> 
> Hi Kyle, as I understood [the ticket](https://jira.mongodb.org/browse/DRIVERS-1150), we just need to copy instructions from transactions spec to retryable writes spec. The behaviour is tested [here](https://github.com/mongodb/specifications/blob/master/source/transactions/tests/legacy/retryable-writes.yml#L160)

Sounds good to me, I'll approve.

2023-12-15 14:20 UTC, kkloberdanz approved these changes

2023-12-19 08:23 UTC, merged