DRIVERS-2732 CSFLE/QE KMIP support for encrypt/decrypt
mongodb/specifications pull request #1507
Opened 2024-02-08 19:41 UTC by adriandole

Please complete the following before merging:

- [x] Update changelog.
- [x] Make sure there are generated JSON files from the YAML test files.
- [x] Test changes in at least one language driver. [C implementation](https://github.com/mongodb/mongo-c-driver/pull/1531/files)
- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded
  clusters, and serverless).

2024-02-09 19:37 UTC, kevinAlbs commented on source/client-side-encryption/tests/legacy/kmipKMS.yml
The legacy tests are generated by templates. Suggest adding a kmipKMS.yml.template. That may resolve the failing GitHub action.

2024-02-12 20:37 UTC, kevinAlbs reviewed
Looks good overall. Suggest removing one of the `delegated` options to simplify the interface.

I suggest waiting until corresponding drivers-evergreen-tools changes (for new KMIP key?), libmongocrypt changes, and C driver changes are approved before merging. The reviews for those changes may reveal required test changes.

2024-02-12 20:37 UTC, kevinAlbs commented on source/client-side-encryption/client-side-encryption.rst
> +      delegated: boolean; // If true (recommended), the KMS provider will perform DEK encryption and decryption. Defaults to false.
Can either `KMIPKMSOptions.delegated` or `masterKey.delegated` options be removed? I expect both are not needed for this feature.

`KMIPKMSOptions.delegated` can be true, false, or unset. `masterKey.delegated` can be true, false, or unset. Including both options may require additional testing and documentation to describe which option applies when they have differing values:

  | KMIPKMSOptions.delegated true | KMIPKMSOptions.delegated false | KMIPKMSOptions.delegated unset
-- | -- | -- | --
**masterKey.delegated true** | Delegated. | ? | Delegated.
**masterKey.delegated false** | ? | Not delegated. | Not delegated.
**masterKey.delegated unset** | Delegated. | Not delegated. | Not delegated.

</div></b>

2024-02-14 19:20 UTC, kevinAlbs approved these changes
LGTM with one additional spec update.

2024-02-14 19:20 UTC, kevinAlbs commented on source/client-side-encryption/client-side-encryption.rst
> +      delegated: boolean; // If true (recommended), the KMS provider will perform DEK encryption and decryption. Defaults to false.
```suggestion
```

2024-03-18 13:46 UTC, katcharov approved these changes
LGTM

2024-03-20 11:46 UTC, kevinAlbs requested changes
The client-side-encryption.rst file was converted to markdown. client-side-encryption.rst now has this note:

> This specification has been converted to Markdown and renamed to
  `client-side-encryption.md <client-side-encryption.md>`_.  
>  Use the link above to access the latest version of the specification as the
  current reStructuredText file will no longer be updated.

Prior to merging, apply the changes to the markdown file and revert the reStructuredText changes.

2024-03-21 19:42 UTC, kevinAlbs approved these changes

2024-03-25 17:55 UTC, merged