CSOT tests: Expect withTransaction to propagate errors
mongodb/specifications pull request #1553
Opened 2024-03-21 17:26 UTC by rozza

DRIVERS-2871

Please complete the following before merging:

- [ ] Update changelog.
- [ ] Make sure there are generated JSON files from the YAML test files.
- [ ] Test changes in at least one language driver.
- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded
  clusters, and serverless).

2024-03-21 17:34 UTC, rozza commented on source/client-side-operations-timeout/tests/convenient-transactions.yml
> +          - commandStartedEvent:
As `withTransaction` expects an error, then an `abortTransaction` event will be issued.

2024-03-26 18:00 UTC, ShaneHarvey requested changes

2024-03-26 18:00 UTC, ShaneHarvey commented on source/client-side-operations-timeout/tests/convenient-transactions.yml
> +          isClientError: true
[In PyMongo](https://github.com/mongodb/mongo-python-driver/blob/f7a7b5a3329981cf39edfa4246578960796da825/test/unified_format.py#L1448-L1449) ([and Go](https://github.com/mongodb/mongo-go-driver/blob/f192906/mongo/integration/unified/operation.go#L32-L43)) the "expectError" on the insertOne above causes the test runner to catch, validate, and the ignore the exception so it never reaches the withTransaction block. So this new test would fail. Is it a bug that Java propagates the exception?

2024-03-26 20:59 UTC, ShaneHarvey commented on source/client-side-operations-timeout/tests/convenient-transactions.yml
> +          isClientError: true
Oh I see. This was recently changed in https://jira.mongodb.org/browse/DRIVERS-1709 but wasn't documented in the UTR spec itself. The only reference is in the jira ticket:
> Ensure that neither ignoreResultAndError nor expectError interfere with propagating exceptions from a callback operation to withTransaction. This came up with the [Java driver's POC](https://github.com/mongodb/specifications/pull/1505#discussion_r1488378728).

2024-03-26 21:56 UTC, ShaneHarvey commented on source/client-side-operations-timeout/tests/convenient-transactions.yml
> +          isClientError: true
Ah I was looking at the old RST version. I is documented in the markdown version: https://github.com/mongodb/specifications/blob/master/source/unified-test-format/unified-test-format.md#withtransaction

2024-04-15 16:16 UTC, rozza commented on source/client-side-operations-timeout/tests/convenient-transactions.yml
> +          isClientError: true
To clarify was this change correct?

2024-04-15 22:26 UTC, ShaneHarvey commented on source/client-side-operations-timeout/tests/convenient-transactions.yml
> +          isClientError: true
Yes this change is correct given the new rules for handling errors in the UTR.

2024-04-15 22:26 UTC, ShaneHarvey approved these changes

2024-05-02 08:38 UTC, merged