DRIVERS-2789 Convert Another SDAM Spec File to Markdown
mongodb/specifications pull request #1582
Opened 2024-05-09 02:34 UTC by blink1073

Please complete the following before merging:

- [x] Update changelog.
- [ ] Make sure there are generated JSON files from the YAML test files.
- [ ] Test changes in at least one language driver.
- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded
  clusters, and serverless).

2024-05-09 02:35 UTC, blink1073 commented
@W-A-James we missed a file last time.  :smile:

2024-05-10 19:45 UTC, W-A-James requested changes
Just one small change

2024-05-10 19:45 UTC, W-A-James commented on source/server-discovery-and-monitoring/server-discovery-and-monitoring.md
> +```
Can we make this a python code block?

2024-05-11 01:54 UTC, blink1073 commented on source/server-discovery-and-monitoring/server-discovery-and-monitoring.md
> +```
Done!

2024-05-24 17:59 UTC, merged