DRIVERS-2881 Render documentation on ReadTheDocs
mongodb/specifications pull request #1584
Opened 2024-05-14 11:49 UTC by blink1073

Please complete the following before merging:

- [ ] Update changelog.
- [ ] Make sure there are generated JSON files from the YAML test files.
- [ ] Test changes in at least one language driver.
- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded
  clusters, and serverless).

2024-05-14 11:50 UTC, blink1073 commented on README.md
> -When developing specifications -- and the drivers themselves -- we follow the following principles:
I moved this to its own file in the source tree since it was referenced from the CMAP spec.

2024-05-14 11:51 UTC, blink1073 commented
> http://specifications.readthedocs.io/en/latest/?badge=latest → Status: 404

This is expected until we have our first successful build.

2024-05-28 14:48 UTC, Jibola requested changes

2024-05-28 20:32 UTC, Jibola approved these changes
LGTM

2024-05-28 20:35 UTC, merged