Commit generated files automatically
mongodb/specifications pull request #1686
Opened 2024-10-28 14:12 UTC by GromNaN

Instead of asking us to regenerate files locally when forgotten, it might as well be done directly by the GitHub Action.

2024-10-28 14:18 UTC, alcaeus requested changes

2024-10-28 14:49 UTC, GromNaN commented on .github/workflows/json-regenerate-check.yml
> +        uses: stefanzweifel/git-auto-commit-action@v5
Added, but that was not necessary when I tried [on my own fork](https://github.com/GromNaN/mongodb-specifications/pull/1).

2024-10-28 15:10 UTC, GromNaN commented on .github/workflows/json-regenerate-check.yml
> +        uses: stefanzweifel/git-auto-commit-action@v5
Yes, that leads to this commit: https://github.com/mongodb/specifications/commit/7f27d57440da24c28afadea6b143993b17d692f0

Let me try again.

2024-10-28 15:28 UTC, GromNaN commented on .github/workflows/json-regenerate-check.yml
> +        uses: stefanzweifel/git-auto-commit-action@v5
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/e5107f70-354d-4ab2-9d5c-ab2f9108ee41">

2024-10-28 16:23 UTC, alcaeus approved these changes

2024-10-29 07:27 UTC, alcaeus commented
@GromNaN I believe rebasing this branch on top of master will fix the lint failure (which was fixed by #1689).

2024-10-29 09:53 UTC, merged