remove references to getLastError
mongodb/specifications pull request #1698
Opened 2024-10-29 20:57 UTC by W-A-James

Please complete the following before merging:

- [ ] Update changelog.
- [ ] Test changes in at least one language driver.
- [ ] Test these changes against all server versions and topologies (including standalone, replica set, sharded
    clusters, and serverless).

2024-10-30 22:24 UTC, W-A-James commented on source/driver-bulk-update.rst
Note: removed since everything in this document seemed to pertain to behaviour that was current in versions <= 2.6

2024-10-30 22:47 UTC, ShaneHarvey requested changes

2024-10-30 22:47 UTC, ShaneHarvey commented on source/driver-bulk-update.rst
I suggest we add this back and open a new drivers ticket to remove this spec.

2024-10-30 22:47 UTC, ShaneHarvey commented on source/read-write-concern/read-write-concern.md
> +2. Commands supporting a write concern MUST send any non-default acknowledged write concern to the server in the
`non-default acknowledged write concern` -> `non-default write concern`. Unack'd writeConcerns need to be sent to the server too.

2024-10-30 22:47 UTC, ShaneHarvey commented on source/read-write-concern/read-write-concern.md
> +3. FindAndModify helper methods MUST NOT send a write concern when the MaxWireVersion is less than 4.
We can remove this since all drivers have dropped support for wire version <=4. 7 is the current min.

2024-10-30 22:47 UTC, ShaneHarvey commented on source/read-write-concern/read-write-concern.md
> +4. Helper methods for other commands that write MUST NOT send a write concern when the MaxWireVersion is less than 5.
We can remove this for the same reason.

2024-11-11 14:30 UTC, nbbeeken approved these changes

2024-11-11 16:04 UTC, dariakp requested changes

2024-11-11 16:04 UTC, dariakp commented on source/server-discovery-and-monitoring/server-discovery-and-monitoring.md
> +- 2024-10-29: Removed references to `getLastError`
Bookmark to make sure to update the changelog to the current date once all other comments are addressed

2024-11-11 16:04 UTC, dariakp commented on source/server_write_commands/server_write_commands.md
> +- 2024-10-30: Add note that getLastError has been removed from the server.
Bookmark to make sure to update the changelog to the current date once all other comments are addressed

2024-11-11 19:25 UTC, ShaneHarvey approved these changes

2024-11-11 19:52 UTC, dariakp approved these changes

2024-11-11 20:04 UTC, W-A-James commented
Merging, will file ticket to remove driver-bulk-update spec

2024-11-11 20:04 UTC, merged