SPEC-1548 Allow 0 for min/max pool size and fully test cmap URI options
mongodb/specifications pull request #859
Opened 2020-09-30 21:28 UTC by saghm

2020-09-30 22:21 UTC, divjotarora approved these changes

2020-09-30 22:34 UTC, behackett commented
What does 0 mean in most drivers? "No limit" or "no pooled connections"?

2020-09-30 22:44 UTC, saghm commented
maxPoolSize=0 is already described in the CMAP spec as meaning "no limit". For some historical context, when the URI options spec was first written, the CMAP spec didn't exist yet, and `maxPoolSize` was defined as being only a positive integer. CMAP was later written, and from the start defined `maxPoolSize=0` as meaning no limit on the pool size, but the PR to the URI options spec add the new information from the CMAP spec mistakenly omitted updating the description of what values are allowed. SPEC-1548 was filed after @dmitry-lukyanov noticed this discrepancy, and based on both the fact that disallowing 0 would cause breaking changes in drivers that followed the CMAP spec and the assumption that drivers are more likely to have implemented their connections pools following the CMAP spec's guidelines rather than the URI option spec's description, this PR is updating the URI options spec to follow to the language of the CMAP spec.

2020-09-30 22:53 UTC, behackett commented
Great. Thanks for the explainer. Carry on.

2020-10-01 07:55 UTC, alcaeus commented
@saghm shouldn't the language for `minPoolSize` also be changed to "non-negative integer", especially since you add tests confirming that specifying "0" for `minPoolSize` shouldn't break?

2020-10-01 19:29 UTC, saghm commented
Yes, you're correct! I've updated it now

2020-10-01 21:26 UTC, DmitryLukyanov approved these changes
LGTM

2020-10-08 09:33 UTC, alcaeus requested changes

2020-10-08 09:33 UTC, alcaeus commented on source/uri-options/uri-options.rst
> +     - The number of connections the driver should create and main in the pool even when no operations are occurring
Wording is off here. "should create and keep in the pool" sounds more like what's intended.

2020-10-12 18:01 UTC, alcaeus approved these changes

2020-10-12 18:07 UTC, merged