DRIVERS-1293: Remove deprecated terms from transaction specs
mongodb/specifications pull request #973
Opened 2021-04-26 20:42 UTC by JamesKovacs

2021-05-03 12:33 UTC, durran requested changes

2021-05-03 12:33 UTC, durran commented on source/transactions/tests/legacy/mongos-recovery-token.yml
> +      # Fail isMaster/hello to prevent the heartbeat requested directly after the
Should this be hello/legacy hello?

2021-05-03 12:33 UTC, durran commented on source/transactions/tests/legacy/pin-mongos.yml
> +      # Fail isMaster/hello to prevent the heartbeat requested directly after the
hello/legacy hello

2021-05-06 00:10 UTC, JamesKovacs commented on source/transactions/tests/legacy/mongos-recovery-token.yml
> +      # Fail isMaster/hello to prevent the heartbeat requested directly after the
Good point. Updated.

2021-05-06 00:11 UTC, JamesKovacs commented on source/transactions/tests/legacy/pin-mongos.yml
> +      # Fail isMaster/hello to prevent the heartbeat requested directly after the
Good point. Updated.

2021-05-10 15:15 UTC, durran approved these changes
LGTM

2021-05-10 21:07 UTC, iwysiu approved these changes

2021-05-10 21:13 UTC, merged