DRIVERS-1721: Remove directConnection=false tests for LB mode
mongodb/specifications pull request #979
Opened 2021-05-03 12:09 UTC by durran

2021-05-03 15:58 UTC, jyemin reviewed
I

2021-05-03 15:58 UTC, jyemin commented on source/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-directConnection-errors.yml
> -# The TXT record for test20.test.build.10gen.cc contains loadBalanced=true. There is no corresponding test for
Instead of deleting this test, can we instead change it so that it asserts that `directConnection=false` does not error?

2021-05-04 15:48 UTC, jyemin approved these changes
LGTM

2021-05-04 21:06 UTC, ShaneHarvey requested changes

2021-05-04 21:06 UTC, ShaneHarvey commented on source/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-directConnection.yml
> +    ssl: true
Please add `directConnection: false`

2021-05-05 19:30 UTC, durran commented on source/initial-dns-seedlist-discovery/tests/load-balanced/loadBalanced-directConnection.yml
> +    ssl: true
Added

2021-05-05 19:33 UTC, ShaneHarvey approved these changes

2021-05-06 13:36 UTC, merged